// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/driscollos/config/internal/sourcer (interfaces: Sourcer)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock-data-sourcer.go -package=mocks . Sourcer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSourcer is a mock of Sourcer interface.
type MockSourcer struct {
	ctrl     *gomock.Controller
	recorder *MockSourcerMockRecorder
	isgomock struct{}
}

// MockSourcerMockRecorder is the mock recorder for MockSourcer.
type MockSourcerMockRecorder struct {
	mock *MockSourcer
}

// NewMockSourcer creates a new mock instance.
func NewMockSourcer(ctrl *gomock.Controller) *MockSourcer {
	mock := &MockSourcer{ctrl: ctrl}
	mock.recorder = &MockSourcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourcer) EXPECT() *MockSourcerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSourcer) Get(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockSourcerMockRecorder) Get(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSourcer)(nil).Get), path)
}

// HotReload mocks base method.
func (m *MockSourcer) HotReload(ctx context.Context, onChange func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HotReload", ctx, onChange)
}

// HotReload indicates an expected call of HotReload.
func (mr *MockSourcerMockRecorder) HotReload(ctx, onChange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HotReload", reflect.TypeOf((*MockSourcer)(nil).HotReload), ctx, onChange)
}

// Source mocks base method.
func (m *MockSourcer) Source(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Source", path)
}

// Source indicates an expected call of Source.
func (mr *MockSourcerMockRecorder) Source(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockSourcer)(nil).Source), path)
}
