// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/driscollos/config/internal/sourcer/terminal-reader (interfaces: TerminalReader)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock-terminal-reader.go -package=mocks . TerminalReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTerminalReader is a mock of TerminalReader interface.
type MockTerminalReader struct {
	ctrl     *gomock.Controller
	recorder *MockTerminalReaderMockRecorder
	isgomock struct{}
}

// MockTerminalReaderMockRecorder is the mock recorder for MockTerminalReader.
type MockTerminalReaderMockRecorder struct {
	mock *MockTerminalReader
}

// NewMockTerminalReader creates a new mock instance.
func NewMockTerminalReader(ctrl *gomock.Controller) *MockTerminalReader {
	mock := &MockTerminalReader{ctrl: ctrl}
	mock.recorder = &MockTerminalReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTerminalReader) EXPECT() *MockTerminalReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTerminalReader) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTerminalReaderMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTerminalReader)(nil).Get), key)
}
